#source 'https://github.com/CocoaPods/Specs.git'
#project 'LHZTestIOS.xcodeproj'
target 'LHZTestIOS' do
   platform:ios,'8.0'
#   xcodeproj 'LHZTestIOS.xcodeproj'
    #自动布局
    pod 'Masonry','1.0.2'
    #网络请求
    pod 'AFNetworking','3.1.0'
    #图片下载
    pod 'SDWebImage','3.7.1'
    #YYKIT
    #pod 'YYKit'
    pod 'YYModel'
    pod 'YYCategories'
    pod 'YYCache'
    #HUD
    pod 'SVProgressHUD'
    pod 'IQKeyboardManager'
end
