platform :ios, '9.0'

#去掉pod警告
inhibit_all_warnings!
#use_frameworks!
target 'SwiftT' do
    #网络请求
    pod 'Alamofire', '~> 4.7.3'
    #HUD
    pod 'SVProgressHUD', '~> 2.2.5'
    #自动布局
    pod 'SnapKit', '~> 4.0.0'
    #上拉下拉刷新
    pod 'MJRefresh', '~> 3.1.15.3'
    #加载网络图片
    pod 'SDWebImage', '~> 5.0.0-beta'
end
